namespace ShpGck
{
    public enum GeckoCommand : byte
    {
        Write8 = 0x01,
        Write16 = 0x02,
        Write32 = 0x03,
        ReadMemory = 0x04,
        ReadMemoryKernel = 0x05,
        ValidateAddressRange = 0x06,
        MemoryDisassemble = 0x08,
        ReadMemoryCompressed = 0x09,
        ReadKernel = 0x0B,
        WriteKernel = 0x0C,
        TakeScreenshot = 0x0D,
        UploadMemory = 0x41,
        ServerStatus = 0x50,
        GetDataBufferSize = 0x51,
        ReadFile = 0x52,
        ReadDirectory = 0x53,
        ReplaceFile = 0x54,
        GetCodeHandlerAddress = 0x55,
        ReadThreads = 0x56,
        AccountIdentifier = 0x57,
        WriteScreen = 0x58,
        FollowPointer = 0x60,
        RemoteProcudureCode = 0x70,
        GetSymbol = 0x71,
        MemorySearch32 = 0x72,
        AdvancedMemorySearch = 0x73,
        ExecuteAssembly = 0x81,
        PauseConsole = 0x82,
        ResumeConsole = 0x83,
        IsConsolePaused = 0x84,
        ServerVersion = 0x99,
        GetOsVersion = 0x9A,
        SetDataBreakPoint = 0xA0,
        SetInstructureBreakPoint = 0xA1,
        ToggleBreakPoint = 0xA5,
        RemoveAllBreakPoints = 0xA6,
        PokeRegisters = 0xA7,
        StackTrace = 0xA8,
        GetEntryPointAddress = 0xB1,
        RunKernelCopyService = 0xCD,
        IOSUHaxReadFile = 0xD0,
        GetVersionHash = 0xE0,
        PersistAssembly = 0xE1,
        ClearAssembly = 0xE2
    }
}
